version: '3.7'

services:  
  client:
    image: workshop/backend
    build: .
    ports:
      - 8888:8000
    environment:
      - DB_HOST=db
      - DB_USER=root 
      - DB_PASSWORD=example 
      - DB_NAME=workshop
      - LOG_LEVEL=debug

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"  
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
